In [241]:
import pandas as pd

In [243]:
df=pd.read_csv("zomato.csv")

In [245]:
df.head(10)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari
5,https://www.zomato.com/bangalore/timepass-dinn...,"37, 5-1, 4th Floor, Bosco Court, Gandhi Bazaar...",Timepass Dinner,Yes,No,3.8/5,286,+91 9980040002\r\n+91 9980063005,Basavanagudi,Casual Dining,"Onion Rings, Pasta, Kadhai Paneer, Salads, Sal...",North Indian,600,"[('Rated 3.0', 'RATED\n Food 3/5\nAmbience 3/...",[],Buffet,Banashankari
6,https://www.zomato.com/bangalore/rosewood-inte...,"19/1, New Timberyard Layout, Beside Satellite ...",Rosewood International Hotel - Bar & Restaurant,No,No,3.6/5,8,+91 9731716688\r\n080 26740366,Mysore Road,Casual Dining,NaN,"North Indian, South Indian, Andhra, Chinese",800,"[('Rated 5.0', 'RATED\n Awesome food ??Great ...",[],Buffet,Banashankari
7,https://www.zomato.com/bangalore/onesta-banash...,"2469, 3rd Floor, 24th Cross, Opposite BDA Comp...",Onesta,Yes,Yes,4.6/5,2556,080 48653961\r\n080 48655715,Banashankari,"Casual Dining, Cafe","Farmhouse Pizza, Chocolate Banana, Virgin Moji...","Pizza, Cafe, Italian",600,"[('Rated 5.0', 'RATED\n I personally really l...",[],Cafes,Banashankari
8,https://www.zomato.com/bangalore/penthouse-caf...,"1, 30th Main Road, 3rd Stage, Banashankari, Ba...",Penthouse Cafe,Yes,No,4.0/5,324,+91 8884135549\r\n+91 9449449316,Banashankari,Cafe,"Pizza, Mocktails, Coffee, Nachos, Salad, Pasta...","Cafe, Italian, Continental",700,"[('Rated 3.0', ""RATED\n I had been to this pl...",[],Cafes,Banashankari
9,https://www.zomato.com/bangalore/smacznego-ban...,"2470, 21 Main Road, 25th Cross, Banashankari, ...",Smacznego,Yes,No,4.2/5,504,+91 9945230807\r\n+91 9743804471,Banashankari,Cafe,"Waffles, Pasta, Coleslaw Sandwich, Choco Waffl...","Cafe, Mexican, Italian, Momos, Beverages",550,"[('Rated 4.0', ""RATED\n Easy to locate\nVFM 3...",[],Cafes,Banashankari

In [248]:
df.shape

(51717, 17)

In [250]:
df.columns

Index(['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes',
       'phone', 'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)', 'reviews_list', 'menu_item',
       'listed_in(type)', 'listed_in(city)'],
      dtype='object')

In [252]:
df=df.drop(columns=['url', 'address','reviews_list', 'menu_item','listed_in(type)', 'listed_in(city)'])

In [254]:
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people)
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600
...,...,...,...,...,...,...,...,...,...,...,...
51712,Best Brews - Four Points by Sheraton Bengaluru...,No,No,3.6 /5,27,080 40301477,Whitefield,Bar,NaN,Continental,"1,500"
51713,Vinod Bar And Restaurant,No,No,NaN,0,+91 8197675843,Whitefield,Bar,NaN,Finger Food,600
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000"
51715,Chime - Sheraton Grand Bengaluru Whitefield Ho...,No,Yes,4.3 /5,236,080 49652769,"ITPL Main Road, Whitefield",Bar,"Cocktails, Pizza, Buttermilk",Finger Food,"2,500"
51716,The Nest - The Den Bengaluru,No,No,3.4 /5,13,+91 8071117272,"ITPL Main Road, Whitefield","Bar, Casual Dining",NaN,"Finger Food, North Indian, Continental","1,500"

In [256]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines',
       'approx_cost(for two people)'],
      dtype='object')

In [258]:
df.rename(columns={'approx_cost(for two people)':'cost for 2'},inplace= True)

In [260]:
df.columns

Index(['name', 'online_order', 'book_table', 'rate', 'votes', 'phone',
       'location', 'rest_type', 'dish_liked', 'cuisines', 'cost for 2'],
      dtype='object')

In [262]:
df=df.drop_duplicates()

In [264]:
df.shape

(25379, 11)

In [266]:
df.head(5)

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost for 2
0,Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800
1,Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800
2,San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800
3,Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300
4,Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600

In [268]:
df['rate']=df['rate'].str.replace("/"," out of")

C:\Users\Administrator\AppData\Local\Temp\ipykernel_8456\1319738949.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['rate']=df['rate'].str.replace("/"," out of")

In [270]:
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost for 2
0,Jalsa,Yes,Yes,4.1 out of5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800
1,Spice Elephant,Yes,No,4.1 out of5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800
2,San Churro Cafe,Yes,No,3.8 out of5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800
3,Addhuri Udupi Bhojana,No,No,3.7 out of5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300
4,Grand Village,No,No,3.8 out of5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600
...,...,...,...,...,...,...,...,...,...,...,...
51631,Just Parathas,No,No,3.4 out of5,5,+91 7010798475,Brookefield,Quick Bites,NaN,North Indian,250
51632,SeeYa Restaurant,No,No,3.3 out of5,4,+91 9164562939,KR Puram,Quick Bites,NaN,"North Indian, Kerala, Chinese",350
51641,Andhra Spices,No,No,3.2 out of5,4,NaN,Brookefield,Quick Bites,NaN,"Andhra, Chinese, South Indian",NaN
51677,Bhagini,No,No,2.5 out of5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800
51714,Plunge - Sheraton Grand Bengaluru Whitefield H...,No,No,NaN,0,NaN,Whitefield,Bar,NaN,Finger Food,"2,000"

C:\Users\Administrator\AppData\Local\Temp\ipykernel_8456\2438587393.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name']=df['name'].str.lower()

In [272]:
df.isna().sum()

name                0
online_order        0
book_table          0
rate             2990
votes               0
phone             539
location           11
rest_type         108
dish_liked      12774
cuisines           30
cost for 2        143
dtype: int64

In [274]:
df=df.dropna()

In [276]:
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost for 2
0,Jalsa,Yes,Yes,4.1 out of5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800
1,Spice Elephant,Yes,No,4.1 out of5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800
2,San Churro Cafe,Yes,No,3.8 out of5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800
3,Addhuri Udupi Bhojana,No,No,3.7 out of5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300
4,Grand Village,No,No,3.8 out of5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600
...,...,...,...,...,...,...,...,...,...,...,...
51615,Little Onnion,Yes,No,3.8 out of5,134,+91 7780502068\n+91 9963081629,"ITPL Main Road, Whitefield",Casual Dining,"Vegetable Biryani, Dum Biryani, Kheer","Biryani, Andhra",500
51617,Breakfast House,No,No,3.6 out of5,49,080 28413047\n+91 9900020540,"ITPL Main Road, Whitefield",Quick Bites,"Coffee, Vada, Mla Dosa","South Indian, North Indian",300
51620,Fujian Express,Yes,No,3.8 out of5,182,+91 7760075458\n+91 9591852291,"ITPL Main Road, Whitefield",Food Court,"Noodles, Chicken Noodle, Momos, American Chops...","Thai, Chinese, Momos",600
51628,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 out of5,411,+91 9663517066\n+91 9686861135,Bellandur,Casual Dining,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","North Indian, Continental, Asian","1,800"
51677,Bhagini,No,No,2.5 out of5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800

In [278]:
df['cost for 2']=df['cost for 2'].astype(str).replace(",","",regex=True)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_8456\91857722.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cost for 2']=df['cost for 2'].astype(str).replace(",","",regex=True)

In [280]:
df['cost for 2']=pd.to_numeric(df['cost for 2'],errors='coerce')

C:\Users\Administrator\AppData\Local\Temp\ipykernel_8456\1051714728.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cost for 2']=pd.to_numeric(df['cost for 2'],errors='coerce')

In [282]:
df['cost for 1']=df['cost for 2']/2

C:\Users\Administrator\AppData\Local\Temp\ipykernel_8456\1639118195.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['cost for 1']=df['cost for 2']/2

In [284]:
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost for 2,cost for 1
0,Jalsa,Yes,Yes,4.1 out of5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,400.0
1,Spice Elephant,Yes,No,4.1 out of5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,400.0
2,San Churro Cafe,Yes,No,3.8 out of5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,400.0
3,Addhuri Udupi Bhojana,No,No,3.7 out of5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,150.0
4,Grand Village,No,No,3.8 out of5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...
51615,Little Onnion,Yes,No,3.8 out of5,134,+91 7780502068\n+91 9963081629,"ITPL Main Road, Whitefield",Casual Dining,"Vegetable Biryani, Dum Biryani, Kheer","Biryani, Andhra",500,250.0
51617,Breakfast House,No,No,3.6 out of5,49,080 28413047\n+91 9900020540,"ITPL Main Road, Whitefield",Quick Bites,"Coffee, Vada, Mla Dosa","South Indian, North Indian",300,150.0
51620,Fujian Express,Yes,No,3.8 out of5,182,+91 7760075458\n+91 9591852291,"ITPL Main Road, Whitefield",Food Court,"Noodles, Chicken Noodle, Momos, American Chops...","Thai, Chinese, Momos",600,300.0
51628,Nook - Aloft Bengaluru Cessna Business Park,No,Yes,4.2 out of5,411,+91 9663517066\n+91 9686861135,Bellandur,Casual Dining,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","North Indian, Continental, Asian",1800,900.0
51677,Bhagini,No,No,2.5 out of5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,400.0

In [289]:
df['name']=df['name'].str.lower()

C:\Users\Administrator\AppData\Local\Temp\ipykernel_8456\2438587393.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['name']=df['name'].str.lower()

In [291]:
df

,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost for 2,cost for 1
0,jalsa,Yes,Yes,4.1 out of5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800,400.0
1,spice elephant,Yes,No,4.1 out of5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800,400.0
2,san churro cafe,Yes,No,3.8 out of5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800,400.0
3,addhuri udupi bhojana,No,No,3.7 out of5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300,150.0
4,grand village,No,No,3.8 out of5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600,300.0
...,...,...,...,...,...,...,...,...,...,...,...,...
51615,little onnion,Yes,No,3.8 out of5,134,+91 7780502068\n+91 9963081629,"ITPL Main Road, Whitefield",Casual Dining,"Vegetable Biryani, Dum Biryani, Kheer","Biryani, Andhra",500,250.0
51617,breakfast house,No,No,3.6 out of5,49,080 28413047\n+91 9900020540,"ITPL Main Road, Whitefield",Quick Bites,"Coffee, Vada, Mla Dosa","South Indian, North Indian",300,150.0
51620,fujian express,Yes,No,3.8 out of5,182,+91 7760075458\n+91 9591852291,"ITPL Main Road, Whitefield",Food Court,"Noodles, Chicken Noodle, Momos, American Chops...","Thai, Chinese, Momos",600,300.0
51628,nook - aloft bengaluru cessna business park,No,Yes,4.2 out of5,411,+91 9663517066\n+91 9686861135,Bellandur,Casual Dining,"Chicken Quesadilla, Naan, Breakfast Buffet, Ch...","North Indian, Continental, Asian",1800,900.0
51677,bhagini,No,No,2.5 out of5,81,080 65951222,Whitefield,"Casual Dining, Bar","Biryani, Andhra Meal","Andhra, South Indian, Chinese, North Indian",800,400.0

In [293]:
df.to_csv('cleaned data.csv',index=False)